/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Change;

import java.awt.Color;

/**
 *
 * @author TTeemo
 */
public class color extends javax.swing.JFrame {

    /**
     * Creates new form color
     */
    public color() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backgroundPanel = new javax.swing.JPanel();
        colorLabel = new javax.swing.JLabel();
        blueRadioButton = new javax.swing.JRadioButton();
        redRadioButton = new javax.swing.JRadioButton();
        greenRadioButton = new javax.swing.JRadioButton();
        pinkRadioButton = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        colorLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        colorLabel.setForeground(new java.awt.Color(255, 255, 255));
        colorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(colorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(colorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        blueRadioButton.setText("BLUE");
        blueRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueRadioButtonActionPerformed(evt);
            }
        });

        redRadioButton.setText("RED");
        redRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redRadioButtonActionPerformed(evt);
            }
        });

        greenRadioButton.setText("GREEN");
        greenRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenRadioButtonActionPerformed(evt);
            }
        });

        pinkRadioButton.setText("PINK");
        pinkRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinkRadioButtonActionPerformed(evt);
            }
        });

        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blueRadioButton)
                            .addComponent(redRadioButton))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(greenRadioButton)
                            .addComponent(pinkRadioButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(submitButton)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueRadioButton)
                    .addComponent(greenRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redRadioButton)
                    .addComponent(pinkRadioButton))
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blueRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueRadioButtonActionPerformed
        if (blueRadioButton.isSelected() == true) {
            redRadioButton.setEnabled(false);
            greenRadioButton.setEnabled(false);
            pinkRadioButton.setEnabled(false);
        }
        else {
            redRadioButton.setEnabled(true);
            greenRadioButton.setEnabled(true);
            pinkRadioButton.setEnabled(true);
        }
        
    }//GEN-LAST:event_blueRadioButtonActionPerformed

    private void redRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redRadioButtonActionPerformed
        if (redRadioButton.isSelected() == true) {
            blueRadioButton.setEnabled(false);
            greenRadioButton.setEnabled(false);
            pinkRadioButton.setEnabled(false);
        }
        else {
            blueRadioButton.setEnabled(true);
            greenRadioButton.setEnabled(true);
            pinkRadioButton.setEnabled(true);
        }
        
    }//GEN-LAST:event_redRadioButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if (blueRadioButton.isSelected() == true) {
            backgroundPanel.setBackground(Color.BLUE);
            colorLabel.setText("You chooose the color BLUE");
        }
        else if (redRadioButton.isSelected() == true) {
            backgroundPanel.setBackground(Color.RED);
            colorLabel.setText("You chooose the color RED");
        }
        else if (greenRadioButton.isSelected() == true) {
            backgroundPanel.setBackground(Color.GREEN);
            colorLabel.setText("You chooose the color GREEN");
        }
        else if (pinkRadioButton.isSelected() == true) {
            backgroundPanel.setBackground(Color.PINK);
            colorLabel.setText("You chooose the color PINK");
        }
        else {
            colorLabel.setText("Please chooose the color you want");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void greenRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenRadioButtonActionPerformed
        if (greenRadioButton.isSelected() == true) {
            redRadioButton.setEnabled(false);
            blueRadioButton.setEnabled(false);
            pinkRadioButton.setEnabled(false);
        }
        else {
            redRadioButton.setEnabled(true);
            blueRadioButton.setEnabled(true);
            pinkRadioButton.setEnabled(true);
        }
        
    }//GEN-LAST:event_greenRadioButtonActionPerformed

    private void pinkRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinkRadioButtonActionPerformed
        if (pinkRadioButton.isSelected() == true) {
            redRadioButton.setEnabled(false);
            greenRadioButton.setEnabled(false);
            blueRadioButton.setEnabled(false);
        }
        else {
            redRadioButton.setEnabled(true);
            greenRadioButton.setEnabled(true);
            blueRadioButton.setEnabled(true);
        }
        
    }//GEN-LAST:event_pinkRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(color.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(color.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(color.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(color.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new color().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel backgroundPanel;
    public javax.swing.JRadioButton blueRadioButton;
    public javax.swing.JLabel colorLabel;
    public javax.swing.JRadioButton greenRadioButton;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JRadioButton pinkRadioButton;
    public javax.swing.JRadioButton redRadioButton;
    public javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
